import { expect, test } from "bun:test";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createContext, closeContext } from "../../context";
import { insertNode, insertUser, userActor } from "@sermo/core/testing";
import { execute } from "../../operation";
import { getNodeAccess, permissionsSetNodeOp } from "./index";
import { invalidate } from "../../context";
import { writeTx } from "../../db/tx";
test("cross-context invalidation", async () => {
  const path = join(tmpdir(), `sermo-probe-${Date.now()}.db`);
  const a = createContext({ path, migrate: true, config: { validateOutput: true } });
  const b = createContext({ path });
  const admin = userActor(insertUser(a, { groupId: 4 }));
  const m = userActor(insertUser(a));
  const n = insertNode(a, {});
  writeTx(a, () => invalidate(a, "node_tree"));
  expect(getNodeAccess(b, m)(n.id).view).toBe(true);
  await execute(a, permissionsSetNodeOp, admin, { nodeId: n.id, groupId: 2, canView: false, canPost: null, canModerate: null });
  expect(getNodeAccess(b, m)(n.id).view).toBe(false);
  const n2 = insertNode(a, { parentId: n.id });
  expect(getNodeAccess(b, m)(n2.id).view).toBe(false);
  writeTx(a, () => invalidate(a, "node_tree"));
  expect(getNodeAccess(b, m)(n2.id)).toEqual({ view: false, post: false, moderate: false });
  a.sqlite.run(`UPDATE nodes SET parent_id = NULL WHERE id = ${n2.id}`);
  writeTx(a, () => invalidate(a, "node_tree"));
  expect(getNodeAccess(b, m)(n2.id).view).toBe(true);
  closeContext(a); closeContext(b);
});
