import { getOperation } from "@sermo/core";

export type RouteMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
export interface ApiRoute {
  method: RouteMethod;
  path: string;
  operation: string;
  status: 200 | 201;
}

const definitions: readonly [RouteMethod, string, string, (200 | 201)?][] = [
  ["PUT", "/push/subscriptions", "push.subscribe"],
  ["DELETE", "/push/subscriptions", "push.unsubscribe"],
  ["GET", "/push/subscriptions", "push.list"],
  ["GET", "/push/public-key", "push.publicKey"],
  ["GET", "/promotions/criteria", "promotions.criteria"],
  ["GET", "/promotions/log", "promotions.log"],
  ["POST", "/promotions/run", "promotions.run", 201],
  ["GET", "/promotions", "promotions.list"],
  ["POST", "/promotions", "promotions.create", 201],
  ["GET", "/promotions/{promotionId}", "promotions.get"],
  ["PATCH", "/promotions/{promotionId}", "promotions.update"],
  ["DELETE", "/promotions/{promotionId}", "promotions.delete"],
  ["GET", "/users/{userId}/promotions", "promotions.memberStatus"],
  ["PUT", "/users/{userId}/promotions/{promotionId}", "promotions.apply"],
  ["POST", "/reports", "reports.create", 201],
  ["GET", "/reports", "reports.list"],
  ["GET", "/reports/{groupId}", "reports.get"],
  ["PUT", "/reports/{groupId}/state", "reports.setState"],
  ["POST", "/reports/{groupId}/conversation-message", "reports.viewConversationMessage"],
  ["GET", "/approval-queue", "approvals.list"],
  ["PUT", "/moderation/state", "moderation.setState"],
  ["POST", "/moderation/bulk", "moderation.bulk"],
  ["GET", "/moderation/log", "moderatorLog.list"],
  ["GET", "/moderation/word-filters", "wordFilters.list"],
  ["PUT", "/moderation/word-filters", "wordFilters.upsert"],
  ["DELETE", "/moderation/word-filters/{filterId}", "wordFilters.remove"],
  ["POST", "/users/{userId}/warnings", "warnings.create", 201],
  ["GET", "/users/{userId}/warnings", "warnings.list"],
  ["POST", "/users/{userId}/bans", "bans.create", 201],
  ["POST", "/bans/{banId}/lift", "bans.lift"],
  ["POST", "/users/{userId}/restrictions", "restrictions.create", 201],
  ["GET", "/users/{userId}/restrictions", "restrictions.list"],
  ["POST", "/restrictions/{restrictionId}/lift", "restrictions.lift"],
  ["GET", "/posts/{postId}/revisions", "postRevisions.list"],
  ["POST", "/users/{userId}/spam-cleanup", "spamCleanup.start", 201],
  ["GET", "/settings", "settings.get"],
  ["PATCH", "/settings", "settings.update"],
  ["GET", "/files/{fileId}/metadata", "files.get"],
  ["PUT", "/profile/avatar", "images.setAvatar"],
  ["PUT", "/profile/cover", "images.setCover"],
  ["PUT", "/nodes/{nodeId}/icon", "images.setNodeIcon"],
  ["PUT", "/nodes/{nodeId}/cover", "images.setNodeCover"],
  ["GET", "/me", "auth.me"],
  ["GET", "/me/preferences", "preferences.get"],
  ["PATCH", "/me/preferences", "preferences.update"],
  ["GET", "/me/ignored", "users.listIgnored"],
  ["GET", "/watches/threads", "watches.listThreads"],
  ["GET", "/watches/nodes", "watches.listNodes"],
  ["GET", "/groups", "groups.list"],
  ["POST", "/groups", "groups.create", 201],
  ["GET", "/groups/{groupId}", "groups.get"],
  ["PATCH", "/groups/{groupId}", "groups.update"],
  ["DELETE", "/groups/{groupId}", "groups.delete"],
  ["GET", "/users/{userId}/groups", "users.getGroups"],
  ["PUT", "/users/{userId}/groups", "users.setGroups"],
  ["GET", "/permissions/definitions", "permissions.definitions"],
  ["GET", "/permissions/entries", "permissions.list"],
  ["PUT", "/permissions/entries", "permissions.set"],
  ["GET", "/permissions/explain", "permissions.explain"],
  ["GET", "/nodes", "nodes.list"],
  ["POST", "/nodes", "nodes.create", 201],
  ["GET", "/nodes/{nodeId}", "nodes.get"],
  ["PUT", "/nodes/{nodeId}/watch", "nodes.watch"],
  ["DELETE", "/nodes/{nodeId}/watch", "nodes.unwatch"],
  ["PATCH", "/nodes/{nodeId}", "nodes.update"],
  ["GET", "/nodes/{nodeId}/permissions", "permissions.listNode"],
  ["GET", "/nodes/{nodeId}/threads", "threads.list"],
  ["POST", "/nodes/{nodeId}/threads", "threads.create", 201],
  ["GET", "/threads/{threadId}", "threads.get"],
  ["PUT", "/threads/{threadId}/watch", "threads.watch"],
  ["DELETE", "/threads/{threadId}/watch", "threads.unwatch"],
  ["PATCH", "/threads/{threadId}", "threads.update"],
  ["PUT", "/threads/{threadId}/sticky", "threads.setSticky"],
  ["PUT", "/threads/{threadId}/lock", "threads.setLocked"],
  ["POST", "/threads/{threadId}/move", "threads.move"],
  ["DELETE", "/threads/{threadId}", "threads.delete"],
  ["POST", "/threads/{threadId}/restore", "threads.restore"],
  ["PUT", "/threads/{threadId}/read", "threads.markRead"],
  ["GET", "/threads/{threadId}/posts", "posts.list"],
  ["POST", "/threads/{threadId}/posts", "posts.create", 201],
  ["GET", "/posts/{postId}", "posts.get"],
  ["PATCH", "/posts/{postId}", "posts.update"],
  ["DELETE", "/posts/{postId}", "posts.delete"],
  ["POST", "/posts/{postId}/restore", "posts.restore"],
  ["GET", "/users", "users.search"],
  ["GET", "/users/{userId}", "profiles.get"],
  ["PUT", "/users/{userId}/follow", "users.follow"],
  ["DELETE", "/users/{userId}/follow", "users.unfollow"],
  ["GET", "/users/{userId}/followers", "users.listFollowers"],
  ["GET", "/users/{userId}/following", "users.listFollowing"],
  ["PUT", "/users/{userId}/ignore", "users.ignore"],
  ["DELETE", "/users/{userId}/ignore", "users.unignore"],
  ["PATCH", "/profile", "profiles.update"],
  ["GET", "/users/{userId}/profile-posts", "profilePosts.list"],
  ["POST", "/users/{userId}/profile-posts", "profilePosts.create", 201],
  ["GET", "/profile-posts/{profilePostId}", "profilePosts.get"],
  ["PATCH", "/profile-posts/{profilePostId}", "profilePosts.update"],
  ["DELETE", "/profile-posts/{profilePostId}", "profilePosts.delete"],
  ["POST", "/profile-posts/{profilePostId}/restore", "profilePosts.restore"],
  ["GET", "/profile-posts/{profilePostId}/comments", "profileComments.list"],
  ["POST", "/profile-posts/{profilePostId}/comments", "profileComments.create", 201],
  ["GET", "/profile-comments/{commentId}", "profileComments.get"],
  ["PATCH", "/profile-comments/{commentId}", "profileComments.update"],
  ["DELETE", "/profile-comments/{commentId}", "profileComments.delete"],
  ["POST", "/profile-comments/{commentId}/restore", "profileComments.restore"],
  ["GET", "/conversations", "conversations.list"],
  ["POST", "/conversations", "conversations.create", 201],
  ["GET", "/conversations/{conversationId}", "conversations.get"],
  ["GET", "/conversations/{conversationId}/messages", "conversations.listMessages"],
  ["POST", "/conversations/{conversationId}/messages", "conversations.reply", 201],
  ["PUT", "/conversations/{conversationId}/read", "conversations.markRead"],
  ["POST", "/conversations/{conversationId}/leave", "conversations.leave"],
  ["GET", "/reaction-types", "reactionTypes.list"],
  ["POST", "/reaction-types", "reactionTypes.create", 201],
  ["PATCH", "/reaction-types/{reactionTypeId}", "reactionTypes.update"],
  ["GET", "/reactions/{contentType}/{contentId}", "reactions.list"],
  ["PUT", "/reactions/{contentType}/{contentId}", "reactions.set"],
  ["DELETE", "/reactions/{contentType}/{contentId}", "reactions.remove"],
  ["GET", "/search", "search.query"],
  ["GET", "/seo/nodes/{nodeId}", "seo.node"],
  ["GET", "/seo/threads/{threadId}", "seo.thread"],
  ["GET", "/seo/users/{userId}", "seo.profile"],
  ["GET", "/seo/search", "seo.search"],
];

export const routes: readonly ApiRoute[] = definitions.map(([method, path, operation, status]) => ({
  method,
  path,
  operation,
  status: status ?? 200,
}));

export const routeOperations = routes.map((route) => ({
  route,
  op: getOperation(route.operation),
}));
